### ISSUE TITLE
Kawai K4r Patch Updates

### ISSUE THREAD

**Issue by diemonster** [eclab/edisyn#26]
Hi --- loving this editor, thank you for your hard work!

My main issue is that with the Kawai K4r, realtime param changes are not reflected except for on the 'global' page. As such, my issue is almost identical to https://github.com/eclab/edisyn/issues/20.

I realize that the K4/K4r has an archaic MIDI implementation, and there are likely limitations for realtime changes. However,  there is another editor for [Ctrlr](https://ctrlr.org/forums/topic/kawai-k4k4r-controller-done/page/2/) that works with the K4r that _does_ allow for realtime changes, but it is otherwise not as well done as yours (i.e. it cannot accept program changes from the synth).

I'm curious if you would consider implementing an event handler for mouseup events or state changes from the panel(s) that sends a program dump back to the synth. This seems like a potentially more elegant solution than the 'repeated program dump' fallback which is not tied to user actions.

**Comment by eclab** [comment]
I don't have a K4r, but the K4 should respond properly to all of Edisyn's realtime changes: however it won't display them onscreen.  Give me some specific, reproducible examples and I'll try to replicate them on my K4.  Real-time changes should be working fine

**Comment by diemonster** [comment]
@eclab primary example that I can consistently repro is changing any source's course tuning, level, or any envelope param. If it's helpful, I can link to a youtube video showing the behavior on my end.

Worth noting: if I flip a source's "on" switch on and off again, the current state of the panel is transmitted similar to hitting cmd+u.

**Comment by eclab** [comment]
I found the bug.  Caused by fat-fingered modifications I made to the K4 editor to fix some mute issues.  And yes, mute should automatically resend the whole patch (mute can't be sent in real time).  I'll have it out in the next revision.  In the mean time, send me email (see my address on the front of the manual) and tell me what OS you're running I'll build a beta version for you to test.

**Comment by ktivdv** [comment]
I would like the beta version too! I have a k4r and have struggled with it
as well. Sending email...

**Comment by diemonster** [comment]
@eclab finally had a chance to try out the new version w my K4R, and it appears the bug is still present in v25. This is on MacOS 10.14.6. I'd be happy to troubleshoot/build a local version if that helps.

**Comment by diemonster** [comment]
Just confirmed v25 has solved the issue here, closing...
